name: Polypheny-DB Docker CI

on:
    push:
    pull_request:
        types: [ unlabeled ]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Docker Tests (Java 11)
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 11
            -   name: Set env variable
                run: |
                    echo "POLYPHENY_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
            -   name: Create folders for certs
                run: |
                    mkdir $POLYPHENY_HOME/.polypheny
                    mkdir $POLYPHENY_HOME/.polypheny/certs
            -   name: Start Docker container
                run: docker-compose up -d
            -   name: Assemble
                run: ./gradlew assemble
            -   name: Execute Docker tests
                run: ./gradlew dockerTests
