name: Polypheny-DB Adapter Matrix CI

on:
    push:
    pull_request:
        types: [ unlabeled ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                adapter: [ mongodb, hsqldb, monetdb, postgresql, file, cottontail, cassandra ]
        name: Integration Tests (Java 11)
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 11
            -   name: Start Docker container
                run: docker-compose up -d
            -   name: Assemble
                run: ./gradlew assemble

            -   name: Execute integration tests for ${{ matrix.adapter }}
                run: ./gradlew integrationTests -Dstore.default=${{ matrix.adapter }}