name: Polypheny-DB Matrix

on:
    push:
    pull_request:
        types: [ unlabeled ]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                java: [ 8, 11, 15 ]
                os: [ macos-latest, ubuntu-latest, windows-latest ]
        name: Java ${{ matrix.java }} @ ${{ matrix.os }}
        steps:
            -   name: Set env variable
                run: |
                    echo "POLYPHENY_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up JDK
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}
            -   name: Assemble
                run: ./gradlew assemble
            -   name: Execute tests
                run: ./gradlew check